### ISSUE TITLE
Suggested Enhancements for webconfigurator

### ISSUE THREAD

**Issue by carp3-noctem** [YIO-Remote/web-configurator#14]
**Is your feature request related to a problem? Please describe.**
Not Related to anything

**Describe the solution you'd like**
Following Enhancement Ideas came into my mind:
1: Entitie Page - Make Integrations collabsible to get a better overview
2: Entitie Page - Add a Search for Entities a) for each Integration or b) one search for all Integrations
3: Entitie Page - Highlight of same sounding / named entities, when coming from different integrations (e.g. Living Room Light _ Can come from Home Assistant and Homey _)

**Additional context**
Any questions are welcome and i will check as soon as possible and provide an answere.
Thanks for the great Work @Shepless

**Comment by Shepless** [comment]
@carp3-noctem are these features covered now in the configurator?
