### ISSUE TITLE
Smaller Payload Size

### ISSUE THREAD

**Issue by Shepless** [YIO-Remote/web-configurator#25]
Currently, the bundle size is ~20MB which is slow to load from the remote. We should get this as small as possible to improve loading performance.

**Comment by zehnm** [comment]
Serving pre-compressed .gz bundles should be possible with lighttpd. This is not my area of expertise, but I can look into it.
That would reduce the size to under 5 MB. (On-the-fly compression is not helping the poor Pi).
Reducing the bundle size in the first place would be even better :-)

**Comment by Shepless** [comment]
I can get the payload down a significant amount without gzip. Like you say if we went down that path it would need to be pre-zipped so the PI doesn't need to do the processing. Leave it with me, if we need gzip serving I will let you know :)

**Comment by zehnm** [comment]
Great! Small is beautiful :-)
Gzip would be part of the Buildroot custom package build. (Packaging is part of the build, it doesn't download the GitHub release artefact).
I would still go for it since we easily reduce the size by 50%, if not 75%.

**Comment by Shepless** [comment]
@zehnm @martonborzak so even without gzip output I have got the total size down to 1.4MB!

**Comment by martonborzak** [comment]
> @zehnm @martonborzak so even without gzip output I have got the total size down to 1.4MB!

Amazing!
