### ISSUE TITLE
Update serialize-javascript

### ISSUE THREAD

**Issue by martonborzak** [YIO-Remote/web-configurator#7]
GitHub detected a security vulnerability 

https://github.com/YIO-Remote/web-configurator/network/alert/package-lock.json/serialize-javascript/open

**Comment by Shepless** [comment]
I get a 404 on that link bud? Also the security tab doesn't show any errors for me?

**Comment by martonborzak** [comment]
it's in package-lock.json

`"serialize-javascript": ">=2.1.1"`

**Comment by martonborzak** [comment]
@Shepless 
![Screenshot 2019-12-08 at 12 22 30](https://user-images.githubusercontent.com/23139408/70388692-79b68080-19b5-11ea-9814-aa161fe561d3.png)

**Comment by Shepless** [comment]
I need to be able to see it to action it mate. Sometimes the security alerts are superfluous. Also, sometimes it's a dependency, of a dependency, of a dependency so it's not just a simple resolution. I still can't see it though to try and remedy it:

<img width="1037" alt="Screenshot 2019-12-08 at 19 49 54" src="https://user-images.githubusercontent.com/3731526/70395188-20217680-19f4-11ea-8b3f-4151cc1e5801.png">

**Comment by carp3-noctem** [comment]
@Shepless I've resend you an invitation to the Project, ~~it also can be that~~ it is only visible to Organization members. I also see the same entry as @martonborzak
